name: Close Completed Issues

on:
  workflow_dispatch:  # Permette di eseguirla manualmente

jobs:
  close_completed_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
            node-version: '22'

      - name: Install dependencies
        run: npm install @octokit/core

      - name: Close issues with all tasks completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node completedIssue.js
