name: Code Quality and Coverage Check

on: [push, pull_request]

jobs:
  code_quality_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest radon coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest

    - name: Check ciclomatic complexity
      run: |
        radon cc .